name: ci

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        include:
          - php-version: 8.4
          - php-version: 8.5

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: start localstack
        run: ./bin/dev/up
      - name: PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: "${{ matrix.php-version }}"
      - name: tests
        run: ./bin/dev/unittest
